# coding: utf-8

# flake8: noqa
"""
    PeerTube

    The PeerTube API is built on HTTP(S) and is RESTful. You can use your favorite HTTP/REST library for your programming language to use PeerTube. The spec API is fully compatible with [openapi-generator](https://github.com/OpenAPITools/openapi-generator/wiki/API-client-generator-HOWTO) which generates a client SDK in the language of your choice - we generate some client SDKs automatically:  - [Python](https://framagit.org/framasoft/peertube/clients/python) - [Go](https://framagit.org/framasoft/peertube/clients/go) - [Kotlin](https://framagit.org/framasoft/peertube/clients/kotlin)  See the [REST API quick start](https://docs.joinpeertube.org/api/rest-getting-started) for a few examples of using the PeerTube API.  # Authentication  When you sign up for an account on a PeerTube instance, you are given the possibility to generate sessions on it, and authenticate there using an access token. Only __one access token can currently be used at a time__.  ## Roles  Accounts are given permissions based on their role. There are three roles on PeerTube: Administrator, Moderator, and User. See the [roles guide](https://docs.joinpeertube.org/admin/managing-users#roles) for a detail of their permissions.  # Errors  The API uses standard HTTP status codes to indicate the success or failure of the API call, completed by a [RFC7807-compliant](https://tools.ietf.org/html/rfc7807) response body.  ``` HTTP 1.1 404 Not Found Content-Type: application/problem+json; charset=utf-8  {   \"detail\": \"Video not found\",   \"docs\": \"https://docs.joinpeertube.org/api-rest-reference.html#operation/getVideo\",   \"status\": 404,   \"title\": \"Not Found\",   \"type\": \"about:blank\" } ```  We provide error `type` values for [a growing number of cases](https://github.com/Chocobozzz/PeerTube/blob/develop/shared/models/server/server-error-code.enum.ts), but it is still optional. Types are used to disambiguate errors that bear the same status code and are non-obvious:  ``` HTTP 1.1 403 Forbidden Content-Type: application/problem+json; charset=utf-8  {   \"detail\": \"Cannot get this video regarding follow constraints\",   \"docs\": \"https://docs.joinpeertube.org/api-rest-reference.html#operation/getVideo\",   \"status\": 403,   \"title\": \"Forbidden\",   \"type\": \"https://docs.joinpeertube.org/api-rest-reference.html#section/Errors/does_not_respect_follow_constraints\" } ```  Here a 403 error could otherwise mean that the video is private or blocklisted.  ### Validation errors  Each parameter is evaluated on its own against a set of rules before the route validator proceeds with potential testing involving parameter combinations. Errors coming from validation errors appear earlier and benefit from a more detailed error description:  ``` HTTP 1.1 400 Bad Request Content-Type: application/problem+json; charset=utf-8  {   \"detail\": \"Incorrect request parameters: id\",   \"docs\": \"https://docs.joinpeertube.org/api-rest-reference.html#operation/getVideo\",   \"instance\": \"/api/v1/videos/9c9de5e8-0a1e-484a-b099-e80766180\",   \"invalid-params\": {     \"id\": {       \"location\": \"params\",       \"msg\": \"Invalid value\",       \"param\": \"id\",       \"value\": \"9c9de5e8-0a1e-484a-b099-e80766180\"     }   },   \"status\": 400,   \"title\": \"Bad Request\",   \"type\": \"about:blank\" } ```  Where `id` is the name of the field concerned by the error, within the route definition. `invalid-params.<field>.location` can be either 'params', 'body', 'header', 'query' or 'cookies', and `invalid-params.<field>.value` reports the value that didn't pass validation whose `invalid-params.<field>.msg` is about.  ### Deprecated error fields  Some fields could be included with previous versions. They are still included but their use is deprecated: - `error`: superseded by `detail` - `code`: superseded by `type` (which is now an URI)  # Rate limits  We are rate-limiting all endpoints of PeerTube's API. Custom values can be set by administrators:  | Endpoint (prefix: `/api/v1`) | Calls         | Time frame   | |------------------------------|---------------|--------------| | `/*`                         | 50            | 10 seconds   | | `POST /users/token`          | 15            | 5 minutes    | | `POST /users/register`       | 2<sup>*</sup> | 5 minutes    | | `POST /users/ask-send-verify-email` | 3      | 5 minutes    |  Depending on the endpoint, <sup>*</sup>failed requests are not taken into account. A service limit is announced by a `429 Too Many Requests` status code.  You can get details about the current state of your rate limit by reading the following headers:  | Header                  | Description                                                | |-------------------------|------------------------------------------------------------| | `X-RateLimit-Limit`     | Number of max requests allowed in the current time period  | | `X-RateLimit-Remaining` | Number of remaining requests in the current time period    | | `X-RateLimit-Reset`     | Timestamp of end of current time period as UNIX timestamp  | | `Retry-After`           | Seconds to delay after the first `429` is received         |  # CORS  This API features [Cross-Origin Resource Sharing (CORS)](https://fetch.spec.whatwg.org/), allowing cross-domain communication from the browser for some routes:  | Endpoint                    | |------------------------- ---| | `/api/*`                    | | `/download/*`               | | `/lazy-static/*`            | | `/.well-known/webfinger`    |  In addition, all routes serving ActivityPub are CORS-enabled for all origins.   # noqa: E501

    The version of the OpenAPI document: 5.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


# import models into model package
from peertube_api_client.models.abuse import Abuse
from peertube_api_client.models.abuse_message import AbuseMessage
from peertube_api_client.models.abuse_state_constant import AbuseStateConstant
from peertube_api_client.models.abuse_state_set import AbuseStateSet
from peertube_api_client.models.account import Account
from peertube_api_client.models.account_summary import AccountSummary
from peertube_api_client.models.actor import Actor
from peertube_api_client.models.actor_image import ActorImage
from peertube_api_client.models.actor_info import ActorInfo
from peertube_api_client.models.add_playlist200_response import AddPlaylist200Response
from peertube_api_client.models.add_playlist200_response_video_playlist import AddPlaylist200ResponseVideoPlaylist
from peertube_api_client.models.add_plugin_request import AddPluginRequest
from peertube_api_client.models.add_plugin_request_one_of import AddPluginRequestOneOf
from peertube_api_client.models.add_plugin_request_one_of1 import AddPluginRequestOneOf1
from peertube_api_client.models.add_user import AddUser
from peertube_api_client.models.add_user_response import AddUserResponse
from peertube_api_client.models.add_user_response_user import AddUserResponseUser
from peertube_api_client.models.add_video_channel200_response import AddVideoChannel200Response
from peertube_api_client.models.add_video_channel_sync200_response import AddVideoChannelSync200Response
from peertube_api_client.models.add_video_playlist_video200_response import AddVideoPlaylistVideo200Response
from peertube_api_client.models.add_video_playlist_video200_response_video_playlist_element import AddVideoPlaylistVideo200ResponseVideoPlaylistElement
from peertube_api_client.models.add_video_playlist_video_request import AddVideoPlaylistVideoRequest
from peertube_api_client.models.add_video_playlist_video_request_video_id import AddVideoPlaylistVideoRequestVideoId
from peertube_api_client.models.api_v1_abuses_abuse_id_messages_get200_response import ApiV1AbusesAbuseIdMessagesGet200Response
from peertube_api_client.models.api_v1_abuses_abuse_id_messages_post_request import ApiV1AbusesAbuseIdMessagesPostRequest
from peertube_api_client.models.api_v1_abuses_abuse_id_put_request import ApiV1AbusesAbuseIdPutRequest
from peertube_api_client.models.api_v1_abuses_post200_response import ApiV1AbusesPost200Response
from peertube_api_client.models.api_v1_abuses_post200_response_abuse import ApiV1AbusesPost200ResponseAbuse
from peertube_api_client.models.api_v1_abuses_post_request import ApiV1AbusesPostRequest
from peertube_api_client.models.api_v1_abuses_post_request_account import ApiV1AbusesPostRequestAccount
from peertube_api_client.models.api_v1_abuses_post_request_comment import ApiV1AbusesPostRequestComment
from peertube_api_client.models.api_v1_abuses_post_request_video import ApiV1AbusesPostRequestVideo
from peertube_api_client.models.api_v1_custom_pages_homepage_instance_put_request import ApiV1CustomPagesHomepageInstancePutRequest
from peertube_api_client.models.api_v1_plugins_npm_name_settings_put_request import ApiV1PluginsNpmNameSettingsPutRequest
from peertube_api_client.models.api_v1_runners_get200_response import ApiV1RunnersGet200Response
from peertube_api_client.models.api_v1_runners_jobs_get200_response import ApiV1RunnersJobsGet200Response
from peertube_api_client.models.api_v1_runners_jobs_job_uuid_abort_post_request import ApiV1RunnersJobsJobUUIDAbortPostRequest
from peertube_api_client.models.api_v1_runners_jobs_job_uuid_accept_post200_response import ApiV1RunnersJobsJobUUIDAcceptPost200Response
from peertube_api_client.models.api_v1_runners_jobs_job_uuid_accept_post200_response_job import ApiV1RunnersJobsJobUUIDAcceptPost200ResponseJob
from peertube_api_client.models.api_v1_runners_jobs_job_uuid_error_post_request import ApiV1RunnersJobsJobUUIDErrorPostRequest
from peertube_api_client.models.api_v1_runners_jobs_job_uuid_success_post_request import ApiV1RunnersJobsJobUUIDSuccessPostRequest
from peertube_api_client.models.api_v1_runners_jobs_job_uuid_success_post_request_payload import ApiV1RunnersJobsJobUUIDSuccessPostRequestPayload
from peertube_api_client.models.api_v1_runners_jobs_job_uuid_update_post_request import ApiV1RunnersJobsJobUUIDUpdatePostRequest
from peertube_api_client.models.api_v1_runners_jobs_job_uuid_update_post_request_payload import ApiV1RunnersJobsJobUUIDUpdatePostRequestPayload
from peertube_api_client.models.api_v1_runners_jobs_request_post200_response import ApiV1RunnersJobsRequestPost200Response
from peertube_api_client.models.api_v1_runners_jobs_request_post200_response_available_jobs_inner import ApiV1RunnersJobsRequestPost200ResponseAvailableJobsInner
from peertube_api_client.models.api_v1_runners_register_post200_response import ApiV1RunnersRegisterPost200Response
from peertube_api_client.models.api_v1_runners_register_post_request import ApiV1RunnersRegisterPostRequest
from peertube_api_client.models.api_v1_runners_registration_tokens_get200_response import ApiV1RunnersRegistrationTokensGet200Response
from peertube_api_client.models.api_v1_runners_unregister_post_request import ApiV1RunnersUnregisterPostRequest
from peertube_api_client.models.api_v1_server_blocklist_accounts_post_request import ApiV1ServerBlocklistAccountsPostRequest
from peertube_api_client.models.api_v1_server_blocklist_servers_post_request import ApiV1ServerBlocklistServersPostRequest
from peertube_api_client.models.api_v1_server_following_post_request import ApiV1ServerFollowingPostRequest
from peertube_api_client.models.api_v1_server_redundancy_host_put_request import ApiV1ServerRedundancyHostPutRequest
from peertube_api_client.models.api_v1_users_me_avatar_pick_post200_response import ApiV1UsersMeAvatarPickPost200Response
from peertube_api_client.models.api_v1_users_me_notification_settings_put_request import ApiV1UsersMeNotificationSettingsPutRequest
from peertube_api_client.models.api_v1_users_me_notifications_read_post_request import ApiV1UsersMeNotificationsReadPostRequest
from peertube_api_client.models.api_v1_users_me_subscriptions_post_request import ApiV1UsersMeSubscriptionsPostRequest
from peertube_api_client.models.api_v1_users_me_video_playlists_videos_exist_get200_response import ApiV1UsersMeVideoPlaylistsVideosExistGet200Response
from peertube_api_client.models.api_v1_users_me_video_playlists_videos_exist_get200_response_video_id_inner import ApiV1UsersMeVideoPlaylistsVideosExistGet200ResponseVideoIdInner
from peertube_api_client.models.api_v1_users_me_video_quota_used_get200_response import ApiV1UsersMeVideoQuotaUsedGet200Response
from peertube_api_client.models.api_v1_video_channels_channel_handle_banner_pick_post200_response import ApiV1VideoChannelsChannelHandleBannerPickPost200Response
from peertube_api_client.models.api_v1_video_channels_channel_handle_video_playlists_get200_response import ApiV1VideoChannelsChannelHandleVideoPlaylistsGet200Response
from peertube_api_client.models.api_v1_videos_id_comment_threads_post_request import ApiV1VideosIdCommentThreadsPostRequest
from peertube_api_client.models.api_v1_videos_id_rate_put_request import ApiV1VideosIdRatePutRequest
from peertube_api_client.models.api_v1_videos_live_id_sessions_get200_response import ApiV1VideosLiveIdSessionsGet200Response
from peertube_api_client.models.api_v1_videos_ownership_id_accept_post_id_parameter import ApiV1VideosOwnershipIdAcceptPostIdParameter
from peertube_api_client.models.block_status import BlockStatus
from peertube_api_client.models.block_status_accounts_value import BlockStatusAccountsValue
from peertube_api_client.models.block_status_hosts_value import BlockStatusHostsValue
from peertube_api_client.models.comment_thread_post_response import CommentThreadPostResponse
from peertube_api_client.models.comment_thread_response import CommentThreadResponse
from peertube_api_client.models.confirm_two_factor_request_request import ConfirmTwoFactorRequestRequest
from peertube_api_client.models.create_video_transcoding_request import CreateVideoTranscodingRequest
from peertube_api_client.models.custom_homepage import CustomHomepage
from peertube_api_client.models.file_redundancy_information import FileRedundancyInformation
from peertube_api_client.models.follow import Follow
from peertube_api_client.models.get_account_followers200_response import GetAccountFollowers200Response
from peertube_api_client.models.get_account_videos_category_one_of_parameter import GetAccountVideosCategoryOneOfParameter
from peertube_api_client.models.get_account_videos_language_one_of_parameter import GetAccountVideosLanguageOneOfParameter
from peertube_api_client.models.get_account_videos_licence_one_of_parameter import GetAccountVideosLicenceOneOfParameter
from peertube_api_client.models.get_account_videos_tags_all_of_parameter import GetAccountVideosTagsAllOfParameter
from peertube_api_client.models.get_account_videos_tags_one_of_parameter import GetAccountVideosTagsOneOfParameter
from peertube_api_client.models.get_accounts200_response import GetAccounts200Response
from peertube_api_client.models.get_jobs200_response import GetJobs200Response
from peertube_api_client.models.get_me_video_rating import GetMeVideoRating
from peertube_api_client.models.get_my_abuses200_response import GetMyAbuses200Response
from peertube_api_client.models.get_o_auth_token200_response import GetOAuthToken200Response
from peertube_api_client.models.get_user200_response import GetUser200Response
from peertube_api_client.models.get_users200_response import GetUsers200Response
from peertube_api_client.models.get_video_blocks200_response import GetVideoBlocks200Response
from peertube_api_client.models.get_video_captions200_response import GetVideoCaptions200Response
from peertube_api_client.models.import_videos_in_channel_create import ImportVideosInChannelCreate
from peertube_api_client.models.job import Job
from peertube_api_client.models.list_registrations200_response import ListRegistrations200Response
from peertube_api_client.models.live_video_latency_mode import LiveVideoLatencyMode
from peertube_api_client.models.live_video_replay_settings import LiveVideoReplaySettings
from peertube_api_client.models.live_video_response import LiveVideoResponse
from peertube_api_client.models.live_video_session_response import LiveVideoSessionResponse
from peertube_api_client.models.live_video_session_response_replay_video import LiveVideoSessionResponseReplayVideo
from peertube_api_client.models.live_video_update import LiveVideoUpdate
from peertube_api_client.models.mrss_group_content import MRSSGroupContent
from peertube_api_client.models.mrss_peer_link import MRSSPeerLink
from peertube_api_client.models.nsfw_policy import NSFWPolicy
from peertube_api_client.models.notification import Notification
from peertube_api_client.models.notification_actor_follow import NotificationActorFollow
from peertube_api_client.models.notification_actor_follow_following import NotificationActorFollowFollowing
from peertube_api_client.models.notification_comment import NotificationComment
from peertube_api_client.models.notification_list_response import NotificationListResponse
from peertube_api_client.models.notification_video import NotificationVideo
from peertube_api_client.models.notification_video_abuse import NotificationVideoAbuse
from peertube_api_client.models.notification_video_abuse_video import NotificationVideoAbuseVideo
from peertube_api_client.models.notification_video_import import NotificationVideoImport
from peertube_api_client.models.o_auth_client import OAuthClient
from peertube_api_client.models.playback_metric_create import PlaybackMetricCreate
from peertube_api_client.models.playlist_element import PlaylistElement
from peertube_api_client.models.plugin import Plugin
from peertube_api_client.models.plugin_response import PluginResponse
from peertube_api_client.models.put_mirrored_video_request import PutMirroredVideoRequest
from peertube_api_client.models.put_video_playlist_video_request import PutVideoPlaylistVideoRequest
from peertube_api_client.models.register_user import RegisterUser
from peertube_api_client.models.register_user_channel import RegisterUserChannel
from peertube_api_client.models.reorder_video_playlist_request import ReorderVideoPlaylistRequest
from peertube_api_client.models.request_two_factor_request import RequestTwoFactorRequest
from peertube_api_client.models.request_two_factor_response import RequestTwoFactorResponse
from peertube_api_client.models.request_two_factor_response_otp_request import RequestTwoFactorResponseOtpRequest
from peertube_api_client.models.resend_email_to_verify_registration_request import ResendEmailToVerifyRegistrationRequest
from peertube_api_client.models.resend_email_to_verify_user_request import ResendEmailToVerifyUserRequest
from peertube_api_client.models.runner import Runner
from peertube_api_client.models.runner_job import RunnerJob
from peertube_api_client.models.runner_job_admin import RunnerJobAdmin
from peertube_api_client.models.runner_job_parent import RunnerJobParent
from peertube_api_client.models.runner_job_payload import RunnerJobPayload
from peertube_api_client.models.runner_job_runner import RunnerJobRunner
from peertube_api_client.models.runner_job_state import RunnerJobState
from peertube_api_client.models.runner_job_state_constant import RunnerJobStateConstant
from peertube_api_client.models.runner_job_type import RunnerJobType
from peertube_api_client.models.runner_registration_token import RunnerRegistrationToken
from peertube_api_client.models.send_client_log import SendClientLog
from peertube_api_client.models.server_config import ServerConfig
from peertube_api_client.models.server_config_about import ServerConfigAbout
from peertube_api_client.models.server_config_about_instance import ServerConfigAboutInstance
from peertube_api_client.models.server_config_auto_blacklist import ServerConfigAutoBlacklist
from peertube_api_client.models.server_config_auto_blacklist_videos import ServerConfigAutoBlacklistVideos
from peertube_api_client.models.server_config_avatar import ServerConfigAvatar
from peertube_api_client.models.server_config_avatar_file import ServerConfigAvatarFile
from peertube_api_client.models.server_config_avatar_file_size import ServerConfigAvatarFileSize
from peertube_api_client.models.server_config_custom import ServerConfigCustom
from peertube_api_client.models.server_config_custom_admin import ServerConfigCustomAdmin
from peertube_api_client.models.server_config_custom_cache import ServerConfigCustomCache
from peertube_api_client.models.server_config_custom_cache_previews import ServerConfigCustomCachePreviews
from peertube_api_client.models.server_config_custom_followers import ServerConfigCustomFollowers
from peertube_api_client.models.server_config_custom_followers_instance import ServerConfigCustomFollowersInstance
from peertube_api_client.models.server_config_custom_import import ServerConfigCustomImport
from peertube_api_client.models.server_config_custom_instance import ServerConfigCustomInstance
from peertube_api_client.models.server_config_custom_services import ServerConfigCustomServices
from peertube_api_client.models.server_config_custom_services_twitter import ServerConfigCustomServicesTwitter
from peertube_api_client.models.server_config_custom_signup import ServerConfigCustomSignup
from peertube_api_client.models.server_config_custom_theme import ServerConfigCustomTheme
from peertube_api_client.models.server_config_custom_transcoding import ServerConfigCustomTranscoding
from peertube_api_client.models.server_config_custom_transcoding_hls import ServerConfigCustomTranscodingHls
from peertube_api_client.models.server_config_custom_transcoding_resolutions import ServerConfigCustomTranscodingResolutions
from peertube_api_client.models.server_config_custom_transcoding_webtorrent import ServerConfigCustomTranscodingWebtorrent
from peertube_api_client.models.server_config_custom_user import ServerConfigCustomUser
from peertube_api_client.models.server_config_email import ServerConfigEmail
from peertube_api_client.models.server_config_followings import ServerConfigFollowings
from peertube_api_client.models.server_config_followings_instance import ServerConfigFollowingsInstance
from peertube_api_client.models.server_config_followings_instance_auto_follow_index import ServerConfigFollowingsInstanceAutoFollowIndex
from peertube_api_client.models.server_config_import import ServerConfigImport
from peertube_api_client.models.server_config_import_videos import ServerConfigImportVideos
from peertube_api_client.models.server_config_instance import ServerConfigInstance
from peertube_api_client.models.server_config_instance_customizations import ServerConfigInstanceCustomizations
from peertube_api_client.models.server_config_plugin import ServerConfigPlugin
from peertube_api_client.models.server_config_search import ServerConfigSearch
from peertube_api_client.models.server_config_search_remote_uri import ServerConfigSearchRemoteUri
from peertube_api_client.models.server_config_signup import ServerConfigSignup
from peertube_api_client.models.server_config_transcoding import ServerConfigTranscoding
from peertube_api_client.models.server_config_trending import ServerConfigTrending
from peertube_api_client.models.server_config_trending_videos import ServerConfigTrendingVideos
from peertube_api_client.models.server_config_user import ServerConfigUser
from peertube_api_client.models.server_config_video import ServerConfigVideo
from peertube_api_client.models.server_config_video_caption import ServerConfigVideoCaption
from peertube_api_client.models.server_config_video_caption_file import ServerConfigVideoCaptionFile
from peertube_api_client.models.server_config_video_file import ServerConfigVideoFile
from peertube_api_client.models.server_config_video_image import ServerConfigVideoImage
from peertube_api_client.models.server_stats import ServerStats
from peertube_api_client.models.server_stats_videos_redundancy_inner import ServerStatsVideosRedundancyInner
from peertube_api_client.models.uninstall_plugin_request import UninstallPluginRequest
from peertube_api_client.models.update_me import UpdateMe
from peertube_api_client.models.update_user import UpdateUser
from peertube_api_client.models.user import User
from peertube_api_client.models.user_admin_flags import UserAdminFlags
from peertube_api_client.models.user_registration import UserRegistration
from peertube_api_client.models.user_registration_accept_or_reject import UserRegistrationAcceptOrReject
from peertube_api_client.models.user_registration_request import UserRegistrationRequest
from peertube_api_client.models.user_registration_state import UserRegistrationState
from peertube_api_client.models.user_registration_user import UserRegistrationUser
from peertube_api_client.models.user_role import UserRole
from peertube_api_client.models.user_viewing_video import UserViewingVideo
from peertube_api_client.models.user_with_stats import UserWithStats
from peertube_api_client.models.vod_audio_merge_transcoding import VODAudioMergeTranscoding
from peertube_api_client.models.vod_audio_merge_transcoding1 import VODAudioMergeTranscoding1
from peertube_api_client.models.vod_audio_merge_transcoding1_input import VODAudioMergeTranscoding1Input
from peertube_api_client.models.vodhls_transcoding import VODHLSTranscoding
from peertube_api_client.models.vodhls_transcoding1 import VODHLSTranscoding1
from peertube_api_client.models.vod_web_video_transcoding import VODWebVideoTranscoding
from peertube_api_client.models.vod_web_video_transcoding1 import VODWebVideoTranscoding1
from peertube_api_client.models.vod_web_video_transcoding1_input import VODWebVideoTranscoding1Input
from peertube_api_client.models.vod_web_video_transcoding1_output import VODWebVideoTranscoding1Output
from peertube_api_client.models.verify_registration_email_request import VerifyRegistrationEmailRequest
from peertube_api_client.models.verify_user_request import VerifyUserRequest
from peertube_api_client.models.video import Video
from peertube_api_client.models.video_blacklist import VideoBlacklist
from peertube_api_client.models.video_caption import VideoCaption
from peertube_api_client.models.video_category import VideoCategory
from peertube_api_client.models.video_channel import VideoChannel
from peertube_api_client.models.video_channel_all_of_owner_account import VideoChannelAllOfOwnerAccount
from peertube_api_client.models.video_channel_create import VideoChannelCreate
from peertube_api_client.models.video_channel_edit import VideoChannelEdit
from peertube_api_client.models.video_channel_list import VideoChannelList
from peertube_api_client.models.video_channel_list_data_inner import VideoChannelListDataInner
from peertube_api_client.models.video_channel_summary import VideoChannelSummary
from peertube_api_client.models.video_channel_sync import VideoChannelSync
from peertube_api_client.models.video_channel_sync_create import VideoChannelSyncCreate
from peertube_api_client.models.video_channel_sync_list import VideoChannelSyncList
from peertube_api_client.models.video_channel_sync_list_data_inner import VideoChannelSyncListDataInner
from peertube_api_client.models.video_channel_sync_state import VideoChannelSyncState
from peertube_api_client.models.video_channel_update import VideoChannelUpdate
from peertube_api_client.models.video_comment import VideoComment
from peertube_api_client.models.video_comment_thread_tree import VideoCommentThreadTree
from peertube_api_client.models.video_comments_for_xml_inner import VideoCommentsForXMLInner
from peertube_api_client.models.video_constant_number_category import VideoConstantNumberCategory
from peertube_api_client.models.video_constant_number_licence import VideoConstantNumberLicence
from peertube_api_client.models.video_constant_string_language import VideoConstantStringLanguage
from peertube_api_client.models.video_details import VideoDetails
from peertube_api_client.models.video_file import VideoFile
from peertube_api_client.models.video_import import VideoImport
from peertube_api_client.models.video_import_state_constant import VideoImportStateConstant
from peertube_api_client.models.video_imports_list import VideoImportsList
from peertube_api_client.models.video_info import VideoInfo
from peertube_api_client.models.video_language import VideoLanguage
from peertube_api_client.models.video_licence import VideoLicence
from peertube_api_client.models.video_list_response import VideoListResponse
from peertube_api_client.models.video_playlist import VideoPlaylist
from peertube_api_client.models.video_playlist_privacy_constant import VideoPlaylistPrivacyConstant
from peertube_api_client.models.video_playlist_privacy_set import VideoPlaylistPrivacySet
from peertube_api_client.models.video_playlist_type_constant import VideoPlaylistTypeConstant
from peertube_api_client.models.video_playlist_type_set import VideoPlaylistTypeSet
from peertube_api_client.models.video_privacy import VideoPrivacy
from peertube_api_client.models.video_privacy_constant import VideoPrivacyConstant
from peertube_api_client.models.video_privacy_set import VideoPrivacySet
from peertube_api_client.models.video_rating import VideoRating
from peertube_api_client.models.video_redundancy import VideoRedundancy
from peertube_api_client.models.video_redundancy_redundancies import VideoRedundancyRedundancies
from peertube_api_client.models.video_resolution_constant import VideoResolutionConstant
from peertube_api_client.models.video_scheduled_update import VideoScheduledUpdate
from peertube_api_client.models.video_source import VideoSource
from peertube_api_client.models.video_state import VideoState
from peertube_api_client.models.video_state_constant import VideoStateConstant
from peertube_api_client.models.video_stats_overall import VideoStatsOverall
from peertube_api_client.models.video_stats_overall_countries_inner import VideoStatsOverallCountriesInner
from peertube_api_client.models.video_stats_retention import VideoStatsRetention
from peertube_api_client.models.video_stats_retention_data_inner import VideoStatsRetentionDataInner
from peertube_api_client.models.video_stats_timeserie import VideoStatsTimeserie
from peertube_api_client.models.video_stats_timeserie_data_inner import VideoStatsTimeserieDataInner
from peertube_api_client.models.video_streaming_playlists import VideoStreamingPlaylists
from peertube_api_client.models.video_streaming_playlists_hls import VideoStreamingPlaylistsHLS
from peertube_api_client.models.video_streaming_playlists_hls_redundancies_inner import VideoStreamingPlaylistsHLSRedundanciesInner
from peertube_api_client.models.video_token_response import VideoTokenResponse
from peertube_api_client.models.video_token_response_files import VideoTokenResponseFiles
from peertube_api_client.models.video_upload_request_common import VideoUploadRequestCommon
from peertube_api_client.models.video_upload_request_resumable import VideoUploadRequestResumable
from peertube_api_client.models.video_upload_response import VideoUploadResponse
from peertube_api_client.models.video_upload_response_video import VideoUploadResponseVideo
from peertube_api_client.models.video_user_history import VideoUserHistory
from peertube_api_client.models.videos_for_xml_inner import VideosForXMLInner
from peertube_api_client.models.videos_for_xml_inner_enclosure import VideosForXMLInnerEnclosure
from peertube_api_client.models.videos_for_xml_inner_media_community import VideosForXMLInnerMediaCommunity
from peertube_api_client.models.videos_for_xml_inner_media_community_media_statistics import VideosForXMLInnerMediaCommunityMediaStatistics
from peertube_api_client.models.videos_for_xml_inner_media_embed import VideosForXMLInnerMediaEmbed
from peertube_api_client.models.videos_for_xml_inner_media_group_inner import VideosForXMLInnerMediaGroupInner
from peertube_api_client.models.videos_for_xml_inner_media_player import VideosForXMLInnerMediaPlayer
from peertube_api_client.models.videos_for_xml_inner_media_thumbnail import VideosForXMLInnerMediaThumbnail
